### ISSUE TITLE
Documentation of User Exits for Performance Engine

### ISSUE THREAD

**Issue by neilbeesley** [genevaers/User-Documentation#219]
Find/relocate existing documentation for Read/Write/Look-up/Format exits.
Review and add further content as necessary.

**Comment by KipTwitchell** [comment]
Kip to add as a branch to documentation the Word Documents, SAFR Bible Chapter on Exits.doc
and SAFR Programmers Guide.doc in MD.

**Comment by KipTwitchell** [comment]
I loaded the initial documents from the Word originals to AdvancedFeatures/UserExits.
