### ISSUE TITLE
New documentation layout

### ISSUE THREAD

**Issue by ghannington** [genevaers/User-Documentation#228]
I suggest we have a layout with the first level looking like this. 
Please review and add comments and suggestions.

- **Getting Started**
- **Setup and Use**
- **Advanced Features**
- **Reference**

Suggested next levels in tree:

**Getting Started**
- Overview (what it does)
	- High-volume data analysis
	- Easy to develop with a graphical interface
- Overview (Components)
	- A small overview (we don't want to lose people here with TMI )
- Demo
	- Link to how to install and run the Demo

**Setup and Use**

- Installation 
- Other setup info - JCL Parms e.g. EXTRPARM (?) with links to parameters in Reference section

- Basic Concepts
- Basic Skills (user guide style)

User guide style typically contains several examples that describe typical scenarios from start to finish.
E.g. adding and running a first View, based on the Demo data.

Maybe some version of the Training slides can go here, but they will need to be reviewed and edited as they refer to old components that do not exist anymore. 

**Advanced Features**
Maybe some version of the Training slides can go here, but they will need to be reviewed and edited as they refer to old components that do not exist anymore. 

**Reference**

- WB logic text reference
- Parameter file syntax
- Assignment rules

**Comment by rhness** [comment]
This is good. Here are some comments:

- To run the demo, we need to do a complete installation of the workbench and the performance engine. Should we make installation of the demo views and the demo files just part of every installation?

- Should the installation documentation be part of the getting started section?  Typically this section would be referred to just once, but the other sections of the documentation would be referred to multiple times.

- If we move the installation documentation to the Getting Started section, then could we change the section to be something like Basic Features?

**Comment by ghannington** [comment]
I have added the outline of the suggested layout to branch newLayout.
I cleaned out all the other files there except for a few config files - it is still using theme 'just-the-docs' at the moment.
I got Jekyll working locally on my PC to test it out :)

**Comment by rhness** [comment]
We are agreed that this is a good layout.
