### ISSUE TITLE
Proposed changes to Workbench Security Overview topic

### ISSUE THREAD

**Issue by michael-shapiro** [genevaers/User-Documentation#249]
Below are my thoughts about Workbench Security Overview topic.

I think that details about environments, users, groups, and migration should be the separate topics. In those topics we can provide “how to” steps.

This is how I would explain a Workbench Security.

Workbench Security Overview
A Workbench has three levels of security. First, a Workbench User should have a permission to access a Workbench metadata database. Database connection parameters are defined using a Workbench Connection.

Next level is that a User must be defined in a Workbench database and belongs to a Group. All database permissions are defined per Group/Environment combination. A Group and Environment is a many-to-many relationship. A Group can access multiple environments and environment can be accessed by multiple groups.

A third security level is based on a role that is assigned for a Group/Environment combination. A workbench has the following roles:
                System Administrator
                Environment Administrator
                Developer
                Guest

A System Administrator does not have to belong to a Group. A system administrator can create a user, a group, assigned a user to a group, clear environments from metadata and perform any task that an environment administrator, a developer, and a guest can do.

Environment Administrator default security settings allow to modify Group permissions for only environment with Environment Administrator rights, perform metadata migration and all Developer and Guest tasks.

A Developer’s default permissions allow to create, delete, modify, and browse metadata.

A group with a Guest role can only browse metadata.

A system administrator or an environment administrator can override default security settings.

Examples
All metadata are new
Create a User
Create a Group
Assigned a User to a Group
Create an Environment 
Assign Environment to a Group with desired role

New User only
Create a User
Assigned a User to a Group

New Environment only
Create Environment
Assign Environment to a Group with desired role

**Comment by ghannington** [comment]
Thanks for the input. I will have a re-organization of what is there.
